import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { DealFeedItem } from "./types";
import { sampleDealFeedItems } from "./fixtures";

/** Generated by `pnpm ingest` (see `services/ingest/`); gitignored. */
const LIVE_DEALS_PATH = path.join(path.dirname(fileURLToPath(import.meta.url)), "deals-live.json");

function loadLiveDealFeedItems(): DealFeedItem[] | null {
  try {
    if (!existsSync(LIVE_DEALS_PATH)) return null;
    const parsed = JSON.parse(readFileSync(LIVE_DEALS_PATH, "utf8")) as unknown;
    return Array.isArray(parsed) && parsed.length > 0 ? (parsed as DealFeedItem[]) : null;
  } catch {
    // A corrupt/partial write shouldn't ever break the app — fall back to fixtures.
    return null;
  }
}

const liveDealFeedItems = loadLiveDealFeedItems();

/** True when `dealFeedItems` below is real ingested data, false when it's
 * the stubbed fixtures fallback (feed unreachable, or never ingested). */
export const isLiveDealFeed = liveDealFeedItems !== null;

/** Real deals when `services/ingest` has produced `deals-live.json`, else
 * the stubbed fixtures — the app never breaks if a feed is unreachable. */
export const dealFeedItems: DealFeedItem[] = liveDealFeedItems ?? sampleDealFeedItems;

/** Explicit accessor equivalent to the `dealFeedItems` export above, for
 * call sites that prefer a function (e.g. a future on-demand refresh). */
export function liveDeals(): DealFeedItem[] {
  return dealFeedItems;
}
