/**
 * Stubbed, typed fixture data for the Phase 1 web shell. Stands in for the
 * Supabase-backed API until Phase 2+ wires up Best Buy/Walmart adapters.
 */
import type {
  Coupon,
  DealFeedItem,
  Product,
  StoreRetailer,
  VerdictResult,
  WishlistItem,
} from "./types";
import { computeVerdict, type PriceObservation } from "./verdict";

export const NOW = new Date("2026-09-14T09:00:00Z");

export const stores: StoreRetailer[] = [
  { id: "store-bestbuy", slug: "best_buy", name: "Best Buy", role: "tracked" },
  { id: "store-walmart", slug: "walmart", name: "Walmart", role: "tracked" },
  { id: "store-amazon", slug: "amazon", name: "Amazon", role: "awareness" },
  { id: "store-microcenter", slug: "micro_center", name: "Micro Center", role: "awareness" },
];

export const products: Product[] = [
  {
    id: "prod-gpu-4070s",
    title: "GeForce RTX 4070 Super 12GB",
    brand: "NVIDIA",
    category: "Components",
    imageUrl: null,
    upc: "812674024451",
    gtin: null,
    asin: "B0CV1WV1JN",
    wpid: "5044821",
    sku: "6567938",
  },
  {
    id: "prod-ssd-2tb",
    title: "990 Pro 2TB NVMe SSD",
    brand: "Samsung",
    category: "Storage",
    imageUrl: null,
    upc: "887276688453",
    gtin: null,
    asin: "B0BHKFHV24",
    wpid: "1197586529",
    sku: "6534920",
  },
  {
    id: "prod-monitor-27",
    title: 'Odyssey G7 27" 240Hz QHD Monitor',
    brand: "Samsung",
    category: "Monitors",
    imageUrl: null,
    upc: "887276458896",
    gtin: null,
    asin: null,
    wpid: null,
    sku: "6469400",
  },
  {
    id: "prod-keyboard-65",
    title: "Pro 65 Mechanical Keyboard",
    brand: "Keychron",
    category: "Peripherals",
    imageUrl: null,
    upc: null,
    gtin: null,
    asin: "B0CGT4Z1QK",
    wpid: null,
    sku: null,
  },
  {
    id: "prod-headphones-xm5",
    title: "WH-1000XM5 Wireless Noise-Canceling Headphones",
    brand: "Sony",
    category: "Peripherals",
    imageUrl: null,
    upc: "027242920885",
    gtin: null,
    asin: "B09XS7JWHH",
    wpid: "1195693455",
    sku: "6505727",
  },
  {
    id: "prod-laptop-g14",
    title: 'ROG Zephyrus G14 14" Gaming Laptop',
    brand: "ASUS",
    category: "Laptops",
    imageUrl: null,
    upc: null,
    gtin: null,
    asin: "B0CS23S1FT",
    wpid: null,
    sku: "6567214",
  },
  {
    id: "prod-webcam-brio",
    title: "Brio 500 4K Webcam",
    brand: "Logitech",
    category: "Peripherals",
    imageUrl: null,
    upc: "097855178664",
    gtin: null,
    asin: "B0BYD3RCJT",
    wpid: null,
    sku: "6539831",
  },
  {
    id: "prod-psu-850",
    title: "RM850x 850W 80+ Gold PSU",
    brand: "Corsair",
    category: "Components",
    imageUrl: null,
    upc: null,
    gtin: null,
    asin: "B08T64K48W",
    wpid: null,
    sku: "6417935",
  },
  {
    id: "prod-case-4000d",
    title: "4000D Airflow Mid-Tower Case",
    brand: "Corsair",
    category: "Components",
    imageUrl: null,
    upc: null,
    gtin: null,
    asin: "B08K5W2SN6",
    wpid: "1195089240",
    sku: "6417946",
  },
  {
    id: "prod-cpu-7800x3d",
    title: "Ryzen 7 7800X3D Processor",
    brand: "AMD",
    category: "Components",
    imageUrl: null,
    upc: "730143314995",
    gtin: null,
    asin: "B0C9WYSW61",
    wpid: "5044822",
    sku: "6537300",
  },
  {
    id: "prod-mouse-superlight",
    title: "G Pro X Superlight 2 Wireless Mouse",
    brand: "Logitech",
    category: "Peripherals",
    imageUrl: null,
    upc: null,
    gtin: null,
    asin: "B0BQD3V64G",
    wpid: null,
    sku: "6534442",
  },
  {
    id: "prod-ssd-1tb-wd",
    title: "WD_BLACK SN850X 1TB NVMe SSD",
    brand: "Western Digital",
    category: "Storage",
    imageUrl: null,
    upc: "718037882729",
    gtin: null,
    asin: "B0B7CZFP6P",
    wpid: "2938401",
    sku: "6516249",
  },
];

function daysAgo(days: number): string {
  return new Date(NOW.getTime() - days * 86_400_000).toISOString();
}

/** Own-logged daily price history per product, keyed by product id (R-05). */
export const priceHistories: Record<string, PriceObservation[]> = {
  "prod-gpu-4070s": Array.from({ length: 96 }, (_, i) => ({
    price: 599 - Math.round(20 * Math.sin(i / 9)) - (i > 70 ? 30 : 0),
    capturedAt: daysAgo(96 - i),
  })),
  "prod-ssd-2tb": Array.from({ length: 40 }, (_, i) => ({
    price: 149 - Math.round(10 * Math.cos(i / 6)),
    capturedAt: daysAgo(40 - i),
  })),
  "prod-monitor-27": [
    { price: 449, capturedAt: daysAgo(6) },
    { price: 449, capturedAt: daysAgo(5) },
    { price: 429, capturedAt: daysAgo(4) },
    { price: 429, capturedAt: daysAgo(3) },
    { price: 429, capturedAt: daysAgo(2) },
    { price: 399, capturedAt: daysAgo(1) },
  ],
  "prod-keyboard-65": [],
  "prod-headphones-xm5": Array.from({ length: 45 }, (_, i) => ({
    price: 358 - Math.round(15 * Math.sin(i / 7)),
    capturedAt: daysAgo(45 - i),
  })),
  "prod-laptop-g14": Array.from({ length: 120 }, (_, i) => ({
    price: 1899 - Math.round(80 * Math.sin(i / 10)) - (i > 100 ? 150 : 0),
    capturedAt: daysAgo(120 - i),
  })),
  "prod-webcam-brio": Array.from({ length: 10 }, (_, i) => ({
    price: 169 - Math.round(6 * Math.sin(i / 3)),
    capturedAt: daysAgo(10 - i),
  })),
  "prod-psu-850": Array.from({ length: 60 }, (_, i) => ({
    price: 149 - Math.round(12 * Math.cos(i / 8)),
    capturedAt: daysAgo(60 - i),
  })),
  "prod-case-4000d": Array.from({ length: 70 }, (_, i) => ({
    price: 104 - Math.round(8 * Math.sin(i / 9)),
    capturedAt: daysAgo(70 - i),
  })),
  "prod-cpu-7800x3d": Array.from({ length: 35 }, (_, i) => ({
    price: 349 - Math.round(20 * Math.sin(i / 6)),
    capturedAt: daysAgo(35 - i),
  })),
  "prod-mouse-superlight": Array.from({ length: 95 }, (_, i) => ({
    price: 149 - Math.round(18 * Math.sin(i / 11)) - (i > 80 ? 20 : 0),
    capturedAt: daysAgo(95 - i),
  })),
  "prod-ssd-1tb-wd": Array.from({ length: 55 }, (_, i) => ({
    price: 89 - Math.round(7 * Math.cos(i / 7)),
    capturedAt: daysAgo(55 - i),
  })),
};

/** Current sticker price per product, as last observed by the daily logger. */
export const currentPrices: Record<string, number> = {
  "prod-gpu-4070s": 549,
  "prod-ssd-2tb": 129,
  "prod-monitor-27": 399,
  "prod-keyboard-65": 84,
  "prod-headphones-xm5": 348,
  "prod-laptop-g14": 1649,
  "prod-webcam-brio": 149,
  "prod-psu-850": 119,
  "prod-case-4000d": 94,
  "prod-cpu-7800x3d": 379,
  "prod-mouse-superlight": 119,
  "prod-ssd-1tb-wd": 74,
};

export const wishlistItems: WishlistItem[] = [
  {
    id: "wish-1",
    userId: "user-jayam",
    productId: "prod-gpu-4070s",
    thresholdType: "percent",
    thresholdValue: 15,
    createdAt: "2026-06-10T00:00:00Z",
  },
  {
    id: "wish-2",
    userId: "user-jayam",
    productId: "prod-ssd-2tb",
    thresholdType: "absolute",
    thresholdValue: 120,
    createdAt: "2026-08-05T00:00:00Z",
  },
  {
    id: "wish-3",
    userId: "user-jayam",
    productId: "prod-monitor-27",
    thresholdType: "percent",
    thresholdValue: 10,
    createdAt: "2026-08-08T00:00:00Z",
  },
  {
    id: "wish-4",
    userId: "user-jayam",
    productId: "prod-keyboard-65",
    thresholdType: "absolute",
    thresholdValue: 75,
    createdAt: "2026-09-11T00:00:00Z",
  },
  {
    id: "wish-5",
    userId: "user-jayam",
    productId: "prod-headphones-xm5",
    thresholdType: "percent",
    thresholdValue: 20,
    createdAt: "2026-08-01T00:00:00Z",
  },
  {
    id: "wish-6",
    userId: "user-jayam",
    productId: "prod-laptop-g14",
    thresholdType: "absolute",
    thresholdValue: 1700,
    createdAt: "2026-05-20T00:00:00Z",
  },
  {
    id: "wish-7",
    userId: "user-jayam",
    productId: "prod-webcam-brio",
    thresholdType: "percent",
    thresholdValue: 15,
    createdAt: "2026-09-04T00:00:00Z",
  },
  {
    id: "wish-8",
    userId: "user-jayam",
    productId: "prod-cpu-7800x3d",
    thresholdType: "absolute",
    thresholdValue: 330,
    createdAt: "2026-08-11T00:00:00Z",
  },
];

export interface WishlistWithVerdict extends WishlistItem {
  product: Product;
  currentPrice: number;
  verdict: VerdictResult;
}

/** Composes wishlist items with their product + a computed verdict (R-06/R-08). */
export function getWishlistWithVerdicts(): WishlistWithVerdict[] {
  return wishlistItems.map((item) => {
    const product = products.find((p) => p.id === item.productId);
    if (!product) throw new Error(`Unknown product for wishlist item ${item.id}`);
    const currentPrice = currentPrices[item.productId] ?? 0;
    const history = priceHistories[item.productId] ?? [];
    return {
      ...item,
      product,
      currentPrice,
      verdict: computeVerdict(currentPrice, history, NOW),
    };
  });
}

/** Stubbed feed fixtures — the fallback `dealFeedItems` (see `deal-feed.ts`)
 * uses when `services/ingest` hasn't produced live data. */
export const sampleDealFeedItems: DealFeedItem[] = [
  {
    id: "feed-1",
    source: "woot",
    dedupeKey: "woot:refurb-steam-deck-oled",
    title: "Refurbished Steam Deck OLED 512GB",
    url: "https://woot.com/offers/steam-deck-oled-refurb",
    storeSlug: null,
    price: 419,
    discountPercent: 16,
    creatorAttributionUrl: null,
    postedAt: "2026-09-13T14:00:00Z",
  },
  {
    id: "feed-2",
    source: "slickdeals",
    dedupeKey: "slickdeals:external-8271934",
    title: "Micro Center open-box Ryzen 7 7800X3D Processor",
    url: "https://slickdeals.net/f/18271934",
    storeSlug: "micro_center",
    price: 329,
    discountPercent: 22,
    creatorAttributionUrl: "https://slickdeals.net/u/dealhunter22",
    postedAt: "2026-09-13T09:30:00Z",
  },
  {
    id: "feed-3",
    source: "dealnews",
    dedupeKey: "dealnews:external-55210",
    title: "Samsung 990 Pro 2TB NVMe SSD",
    url: "https://dealnews.com/samsung-990-pro-2tb/55210",
    storeSlug: "best_buy",
    price: 129,
    discountPercent: 14,
    creatorAttributionUrl: null,
    postedAt: "2026-09-12T22:10:00Z",
  },
  {
    id: "feed-4",
    source: "woot",
    dedupeKey: "woot:logitech-mx-master-3s",
    title: "Logitech MX Master 3S Mouse",
    url: "https://woot.com/offers/logitech-mx-master-3s",
    storeSlug: null,
    price: 69,
    discountPercent: 30,
    creatorAttributionUrl: null,
    postedAt: "2026-09-12T12:00:00Z",
  },
  {
    id: "feed-5",
    source: "dealnews",
    dedupeKey: "dealnews:external-55231",
    title: "NVIDIA GeForce RTX 4070 Super 12GB Graphics Card",
    url: "https://dealnews.com/nvidia-rtx-4070-super/55231",
    storeSlug: "best_buy",
    price: 549,
    discountPercent: 8,
    creatorAttributionUrl: null,
    postedAt: "2026-09-14T02:40:00Z",
  },
  {
    id: "feed-6",
    source: "slickdeals",
    dedupeKey: "slickdeals:external-8272910",
    title: "Sony WH-1000XM5 Wireless Noise-Canceling Headphones",
    url: "https://slickdeals.net/f/18272910",
    storeSlug: "amazon",
    price: 328,
    discountPercent: 18,
    creatorAttributionUrl: "https://slickdeals.net/u/quietcommute",
    postedAt: "2026-09-13T20:15:00Z",
  },
  {
    id: "feed-7",
    source: "dealnews",
    dedupeKey: "dealnews:external-55244",
    title: 'ASUS ROG Zephyrus G14 14" Gaming Laptop, Ryzen 9 / RTX 4060',
    url: "https://dealnews.com/asus-rog-zephyrus-g14/55244",
    storeSlug: "best_buy",
    price: 1649,
    discountPercent: 15,
    creatorAttributionUrl: null,
    postedAt: "2026-09-11T16:00:00Z",
  },
  {
    id: "feed-8",
    source: "woot",
    dedupeKey: "woot:logitech-brio-500-webcam",
    title: "Logitech Brio 500 4K Webcam",
    url: "https://woot.com/offers/logitech-brio-500",
    storeSlug: null,
    price: 149,
    discountPercent: 12,
    creatorAttributionUrl: null,
    postedAt: "2026-09-10T11:00:00Z",
  },
  {
    id: "feed-9",
    source: "slickdeals",
    dedupeKey: "slickdeals:external-8273102",
    title: "Corsair RM850x 850W 80+ Gold Fully Modular PSU",
    url: "https://slickdeals.net/f/18273102",
    storeSlug: "micro_center",
    price: 109,
    discountPercent: 27,
    creatorAttributionUrl: "https://slickdeals.net/u/wattwise",
    postedAt: "2026-09-13T04:45:00Z",
  },
  {
    id: "feed-10",
    source: "dealnews",
    dedupeKey: "dealnews:external-55258",
    title: "Corsair 4000D Airflow Mid-Tower Case, Black",
    url: "https://dealnews.com/corsair-4000d-airflow/55258",
    storeSlug: "walmart",
    price: 84,
    discountPercent: 16,
    creatorAttributionUrl: null,
    postedAt: "2026-09-12T08:20:00Z",
  },
  {
    id: "feed-11",
    source: "slickdeals",
    dedupeKey: "slickdeals:external-8273580",
    title: "Logitech G Pro X Superlight 2 Wireless Mouse",
    url: "https://slickdeals.net/f/18273580",
    storeSlug: "amazon",
    price: 119,
    discountPercent: 20,
    creatorAttributionUrl: "https://slickdeals.net/u/clickclack",
    postedAt: "2026-09-11T19:30:00Z",
  },
  {
    id: "feed-12",
    source: "dealnews",
    dedupeKey: "dealnews:external-55267",
    title: "WD_BLACK SN850X 1TB NVMe Gaming SSD",
    url: "https://dealnews.com/wd-black-sn850x-1tb/55267",
    storeSlug: "best_buy",
    price: 74,
    discountPercent: 25,
    creatorAttributionUrl: null,
    postedAt: "2026-09-10T15:10:00Z",
  },
  {
    id: "feed-13",
    source: "woot",
    dedupeKey: "woot:anker-737-power-bank",
    title: "Anker 737 PowerCore 24K Portable Charger",
    url: "https://woot.com/offers/anker-737-powercore",
    storeSlug: null,
    price: 99,
    discountPercent: 34,
    creatorAttributionUrl: null,
    postedAt: "2026-09-13T18:20:00Z",
  },
  {
    id: "feed-14",
    source: "slickdeals",
    dedupeKey: "slickdeals:external-8274012",
    title: "Elgato Facecam 4K60 Streaming Camera",
    url: "https://slickdeals.net/f/18274012",
    storeSlug: "amazon",
    price: 179,
    discountPercent: 10,
    creatorAttributionUrl: "https://slickdeals.net/u/streamsetup",
    postedAt: "2026-09-09T13:50:00Z",
  },
  {
    id: "feed-15",
    source: "dealnews",
    dedupeKey: "dealnews:external-55278",
    title: "TP-Link Archer AXE75 Tri-Band WiFi 6E Router",
    url: "https://dealnews.com/tp-link-archer-axe75/55278",
    storeSlug: "walmart",
    price: 139,
    discountPercent: 22,
    creatorAttributionUrl: null,
    postedAt: "2026-09-08T10:40:00Z",
  },
  {
    id: "feed-16",
    source: "woot",
    dedupeKey: "woot:samsung-t9-portable-ssd",
    title: "Samsung T9 2TB Portable SSD",
    url: "https://woot.com/offers/samsung-t9-portable-2tb",
    storeSlug: null,
    price: 149,
    discountPercent: 28,
    creatorAttributionUrl: null,
    postedAt: "2026-09-12T17:05:00Z",
  },
  {
    id: "feed-17",
    source: "slickdeals",
    dedupeKey: "slickdeals:external-8274390",
    title: "Corsair Vengeance 32GB (2x16GB) DDR5-6000 RAM Kit",
    url: "https://slickdeals.net/f/18274390",
    storeSlug: "micro_center",
    price: 89,
    discountPercent: 31,
    creatorAttributionUrl: "https://slickdeals.net/u/ramrunner",
    postedAt: "2026-09-11T06:15:00Z",
  },
  {
    id: "feed-18",
    source: "dealnews",
    dedupeKey: "dealnews:external-55291",
    title: "ASUS ROG Strix B650-A Gaming WiFi Motherboard",
    url: "https://dealnews.com/asus-rog-strix-b650-a/55291",
    storeSlug: "best_buy",
    price: 219,
    discountPercent: 12,
    creatorAttributionUrl: null,
    postedAt: "2026-09-07T21:00:00Z",
  },
  {
    id: "feed-19",
    source: "woot",
    dedupeKey: "woot:blue-yeti-x-microphone",
    title: "Blue Yeti X Professional USB Microphone",
    url: "https://woot.com/offers/blue-yeti-x",
    storeSlug: null,
    price: 119,
    discountPercent: 20,
    creatorAttributionUrl: null,
    postedAt: "2026-09-14T00:30:00Z",
  },
  {
    id: "feed-20",
    source: "slickdeals",
    dedupeKey: "slickdeals:external-8275001",
    title: "Secretlab Titan Evo 2022 Gaming Chair",
    url: "https://slickdeals.net/f/18275001",
    storeSlug: "amazon",
    price: 439,
    discountPercent: 15,
    creatorAttributionUrl: "https://slickdeals.net/u/deskrig",
    postedAt: "2026-09-06T14:25:00Z",
  },
  {
    id: "feed-21",
    source: "dealnews",
    dedupeKey: "dealnews:external-55305",
    title: "LG 34WP65C 34-inch Ultrawide Curved Monitor",
    url: "https://dealnews.com/lg-34wp65c-ultrawide/55305",
    storeSlug: "walmart",
    price: 279,
    discountPercent: 19,
    creatorAttributionUrl: null,
    postedAt: "2026-09-05T09:15:00Z",
  },
  {
    id: "feed-22",
    source: "woot",
    dedupeKey: "woot:apc-back-ups-pro-1500",
    title: "APC Back-UPS Pro 1500VA Battery Backup",
    url: "https://woot.com/offers/apc-back-ups-pro-1500",
    storeSlug: null,
    price: 159,
    discountPercent: 24,
    creatorAttributionUrl: null,
    postedAt: "2026-09-04T12:00:00Z",
  },
  {
    id: "feed-23",
    source: "slickdeals",
    dedupeKey: "slickdeals:external-8275640",
    title: "Wacom Intuos Pro Medium Drawing Tablet",
    url: "https://slickdeals.net/f/18275640",
    storeSlug: "micro_center",
    price: 229,
    discountPercent: 17,
    creatorAttributionUrl: "https://slickdeals.net/u/inkandpixel",
    postedAt: "2026-09-03T17:40:00Z",
  },
  {
    id: "feed-24",
    source: "dealnews",
    dedupeKey: "dealnews:external-55318",
    title: "Canon PIXMA TR8620a All-in-One Wireless Printer",
    url: "https://dealnews.com/canon-pixma-tr8620a/55318",
    storeSlug: "best_buy",
    price: 129,
    discountPercent: 21,
    creatorAttributionUrl: null,
    postedAt: "2026-09-02T08:50:00Z",
  },
  {
    id: "feed-25",
    source: "woot",
    dedupeKey: "woot:netgear-nighthawk-switch",
    title: "Netgear Nighthawk 8-Port Gigabit Ethernet Switch",
    url: "https://woot.com/offers/netgear-nighthawk-switch-8port",
    storeSlug: null,
    price: 49,
    discountPercent: 29,
    creatorAttributionUrl: null,
    postedAt: "2026-09-14T05:10:00Z",
  },
  {
    id: "feed-26",
    source: "slickdeals",
    dedupeKey: "slickdeals:external-8276205",
    title: "Elgato Stream Deck MK.2 15-Key Controller",
    url: "https://slickdeals.net/f/18276205",
    storeSlug: "amazon",
    price: 129,
    discountPercent: 13,
    creatorAttributionUrl: "https://slickdeals.net/u/streamsetup",
    postedAt: "2026-09-01T15:30:00Z",
  },
];

export const coupons: Coupon[] = [
  {
    id: "coupon-1",
    storeRetailerId: "store-bestbuy",
    productId: null,
    code: "BBY-STUDENT10",
    description: "10% off select accessories for students",
    discountPercent: 10,
    discountAmount: null,
    verifiedStatus: "verified",
    lastVerifiedAt: "2026-09-13T18:00:00Z",
    successRate: 0.86,
    successCount: 43,
    totalVotes: 50,
  },
  {
    id: "coupon-2",
    storeRetailerId: "store-walmart",
    productId: null,
    code: "WM-FREESHIP",
    description: "Free shipping, no minimum",
    discountPercent: null,
    discountAmount: null,
    verifiedStatus: "verified",
    lastVerifiedAt: "2026-09-14T02:00:00Z",
    successRate: 0.95,
    successCount: 190,
    totalVotes: 200,
  },
  {
    id: "coupon-3",
    storeRetailerId: "store-bestbuy",
    productId: "prod-monitor-27",
    code: "MONITOR25",
    description: "Reported $25 off monitors over $300",
    discountPercent: null,
    discountAmount: 25,
    verifiedStatus: "quarantined",
    lastVerifiedAt: null,
    successRate: null,
    successCount: 1,
    totalVotes: 9,
  },
  {
    id: "coupon-4",
    storeRetailerId: "store-microcenter",
    productId: null,
    code: "MC-BUILD5",
    description: "5% off a full PC build's parts, rung up together",
    discountPercent: 5,
    discountAmount: null,
    verifiedStatus: "verified",
    lastVerifiedAt: "2026-09-12T19:45:00Z",
    successRate: 0.78,
    successCount: 61,
    totalVotes: 78,
  },
  {
    id: "coupon-5",
    storeRetailerId: "store-amazon",
    productId: null,
    code: "PRIME-TECH15",
    description: "Reported 15% off select electronics for Prime members",
    discountPercent: 15,
    discountAmount: null,
    verifiedStatus: "unverified",
    lastVerifiedAt: null,
    successRate: null,
    successCount: 0,
    totalVotes: 3,
  },
];
